### ISSUE TITLE
The «Sign in with GitHub» on https://cla.js.foundation/ is not working

### ISSUE THREAD

**Issue by ChALkeR** [JSFoundation/cla-assistant#12]
While figuring out what to do with #10, I tried going to https://cla.js.foundation/ to see if I could disable that.

This is what the page https://cla.js.foundation/ looks like for me:
![screenshot_20180723_172233](https://user-images.githubusercontent.com/291301/43082548-fd27bd8a-8e9c-11e8-858c-11bb6904b7a4.png)

There is a scrollbar, but there is just more empty space.

«Sign in with GitHub» and «Sign in» buttons do nothing except for just refreshing the page. Nothing works. 

At the same time, I am signed in at the https://cla.js.foundation/webpack/loader-runner page (but still unable to do anything there).

Just the index page does not work.

**Comment by JSFOwner** [comment]
This is expected behavior. Since the current version of the CLA Assistant does not have user management, any user logging in to that interface would be able to edit configuration on any JSF project so the admin is limited to JSF staff. You would not have been able to correct the comment editing bug from that admin interface. It is a bug somewhere in the source.
