### ISSUE TITLE
How to exclude CLA on specific repositories?

### ISSUE THREAD

**Issue by bebraw** [JSFoundation/cla-assistant#6]
Given CLA assistant is configured on organization level, it gets applied to all repositories below it. Would it be possible to exclude some repository from it?

In webpack's case it adds friction to the documentation process. Do you think there would be any legal implications in skipping the CLA in that case?

**Comment by kborchers** [comment]
It is possible to exclude repos. That said, documentation should not be excluded because you should still be having folks license those contributions. In general, it's just a good idea to ensure people have the right to contribute that documentation and they understand how you will redistribute that contribution. This becomes even more important in one example when your documentation has code samples in it where people may copy/paste that code in their own projects.

**Comment by bebraw** [comment]
Ok, thanks. I think I'll do a pull request template then.

**Comment by d3viant0ne** [comment]
@kborchers - Quick question directly related to the above. For the documentation repos mentioned above ( 3 to be exact ) we currently have a CC 4.0 license in place.

My understanding of the requirements for using the CLA assistant is we need to have the JSF license in place. For those repos that are documentation focused while having code examples as you mentioned above, what is the licensing guidance?

**Comment by kborchers** [comment]
@d3viant0ne This will be dependent upon the situation but in general, we recommend CC4 for docs and specifically calling out what constitutes sample code within those docs and releasing that under CC0. The main reason for that is so that people, especially new developers, that copy code examples and put them in their apps without attribution would not be unwittingly violating the CC4 attribution clause. You do need to be careful though. If your docs use snippets of the actual source, that would still need to be under the main source repository license. Does that help?

Feel free to ask any other questions or give specific scenarios and I'll be happy to give advice and/or get our legal team's opinion if it's a new situation.

**Comment by d3viant0ne** [comment]
That's perfect, thanks for the quick response
