### ISSUE TITLE
Is CLA currently down?

### ISSUE THREAD

**Issue by platinumazure** [JSFoundation/cla-assistant#8]
On the eslint/eslint repo, [this pull request](https://github.com/eslint/eslint/pull/10098) has a pending CLA check on it. I closed and reopened the PR to try to re-trigger the status check, but nothing appears to have changed.

Not sure if this is related, but: When I visited cla.js.foundation, I got a warning that the HTTPS cert might be invalid.

Is the CLA currently down/inoperable? Is there anything we need to do in the repo to make it start working again? Thanks!

**Comment by kborchers** [comment]
Hey @platinumazure, the CLA checker was down for a bit due to an expired license. We have moved all of our licenses to Let's Encrypt which means they expire every 90 days and I am still trying to sort out all of the automation scripts and incorporate them into our maze of Puppet and Ansible configs and that one was missed. This should not be an issue going forward as I should have the automation straightened out by June. Let me know if you continue to have issues and sorry for the hiccup in your processes.

**Comment by platinumazure** [comment]
No worries, thanks for the reply. All is well now, so I'll go ahead and close this.
